### PR TITLE
fix #31

### LINKED ISSUE #31: Problems with chinese text
The tokenization service fails with 500 Error on chinese language text.
image

@balmas comments:
There is this comment in the code:

_PKUSEG_INSTALL_MSG = "install it with `pip install pkuseg==0.0.25` or from https://github.com/lancopku/pkuseg-python"
You could add that to the setup.py file and see if it resolves the problem.

Test case
Τί νεώτερον, ὦ Σώκρατες, γέγονεν,
人物：蘇格拉地 歐雪佛洛（註一）

### PR DESCRIPTION
**Pull request by balmas**
add dependencies for chinese and handle unexpected error

@irina060981 I'm not sure what the problem is with the Docker container and I cannot investigate it right now, but this should enable tokenization of chinese to work.

### CODE REVIEW

**Comment by balmas** [comment]
Actually, it seems you are right about the missing dependencies in the Dockerfile. I'm not sure why I didn't have that problem in production but maybe something with the python-3.7.3-slim image changed.

I also realized I never updated the README to reflect that we are running the service through gunicorn. that's updated now too.

(`docker run -p 5000:5000 tokenizer:latest gunicorn --bind 0.0.0.0:5000 manage:app`)

I hope you'll be able to build and run the image now and verify the fix..

**Comment by irina060981** [comment]
Great!
@balmas - it is successfully build locally and works :)

**Review by irina060981 — APPROVED** [review]
Works well!
As for chinese - I believe that the tokenizer doesn't divide well

From cinese example:
人物：蘇格拉地 歐雪佛洛（註一）

gives the following:
```
{
  "segments": [
    {
      "index": 1,
      "tokens": [
        {
          "alpheios_data_cite": "",
          "alpheios_data_tb_word": "",
          "docIndex": 0,
          "index": 0,
          "line_break_before": false,
          "punct": false,
          "text": "人物：蘇格拉地"
        },
        {
          "alpheios_data_cite": "",
          "alpheios_data_tb_word": "",
          "docIndex": 1,
          "index": 1,
          "line_break_before": false,
          "punct": false,
          "text": "歐雪佛洛（註一"
        },
        {
          "alpheios_data_cite": "",
          "alpheios_data_tb_word": "",
          "docIndex": 2,
          "index": 2,
          "line_break_before": false,
          "punct": true,
          "text": "）"
        }
      ]
    }
  ]
}
```

**Comment by balmas** [comment]
@irina060981 what language code did you use? In my test with 'zh' it worked ok (see the test case)

**Comment by irina060981** [comment]
>@irina060981 what language code did you use? In my test with 'zh' it worked ok (see the test case)
I used `zho` - I think we use 3-chars code in the application.
You are right - `zh` works better :)

**Comment by irina060981** [comment]
I would add libraries for other languages and creates PR - if I would merge it - it will be deployed automatically?

**Comment by balmas** [comment]
At the moment, it only deploys automatically once per week. But it's easy enough to do and hopefully we won't have to many more changes. I will deploy it later today.

As for the codes -- it looks like there was a typo in my language code mappings in mapper.py: I used the 3 character 'zhu' code for chinese instead of 'zho'  . Could you fix that?

**Comment by balmas** [comment]
this PR is deployed now btw.  Will redeploy when #34 is fixed.

**Pull request merged**
