### PR TITLE
Additional language dependencies

### PR DESCRIPTION
**Pull request by irina060981**
For the issue https://github.com/alpheios-project/tokenizer/issues/33

Added support for

Russian: pymorphy2
Ukrainian: pymorphy2
Thai: pythainlp
Vietnamese: Pyvi

### CODE REVIEW

**Review by balmas — APPROVED** [review]
looks ok. Can you please  also fix the 3 char code for chinese per my comments in #31 ? (zho instead of zhu ?) Thanks!

**Comment by irina060981** [comment]
>Can you please also fix the 3 char code for chinese per my comments in #31 ? (zho instead of zhu ?) Thanks!

Fixed

**Comment by balmas** [comment]
@irina060981 and @monzug this is deployed now.  Hopefully the tokenizer will work a little better now for some of these languages.

**Comment by irina060981** [comment]
Thank you, @balmas, for all your help with it :)

**Pull request merged**
